apiVersion: v1
kind: Service
metadata:
  name: advertisements-back
  namespace: prod
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: advertisements-back