spring:
  data:
    mongodb:
      uri:
        mongodb+srv://neda:pXVInw3IpAEuXymk@cluster0.nthx6ns.mongodb.net
      database:
        advertisements

logging:
  level:
    org:
      springframework:
        data:
          convert:
            CustomConversions:
              ERROR
